######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 4 14:41:59 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profile_widget.h
SOURCES += main.cpp profile_widget.cpp
