######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 9 11:19:19 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -g -Wall

# Input
HEADERS += main_window.h
SOURCES += main.cpp main_window.cpp
