######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 4 14:10:32 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
